from __future__ import annotations

from pathlib import Path


def _ps_single_quote(value: str) -> str:
    """Escape a value for PowerShell single-quoted string literals."""
    return "'" + str(value).replace("'", "''") + "'"

_SYSTEMD_UNIT_TEMPLATE = """[Unit]
Description=nightwire {name}
After=network.target

[Service]
WorkingDirectory={working_dir}
ExecStart={exec_start}
{env_lines}Restart=on-failure

[Install]
WantedBy=default.target
"""


def write_systemd_unit(name: str, working_dir: Path, exec_start: str, env: dict[str, str], units_dir: Path) -> Path:
    env_lines = "".join(f"Environment={key}={value}\n" for key, value in env.items())
    content = _SYSTEMD_UNIT_TEMPLATE.format(name=name, working_dir=working_dir, exec_start=exec_start, env_lines=env_lines)
    units_dir.mkdir(parents=True, exist_ok=True)
    path = units_dir / f"nightwire-{name}.service"
    path.write_text(content)
    return path


_LAUNCHD_PLIST_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.nightwire.{name}</string>
    <key>ProgramArguments</key>
    <array>
{program_args}    </array>
    <key>WorkingDirectory</key>
    <string>{working_dir}</string>
    <key>EnvironmentVariables</key>
    <dict>
{env_entries}    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
"""


def write_launchd_plist(name: str, working_dir: Path, argv: list[str], env: dict[str, str], plists_dir: Path) -> Path:
    program_args = "".join(f"        <string>{arg}</string>\n" for arg in argv)
    env_entries = "".join(f"        <key>{k}</key>\n        <string>{v}</string>\n" for k, v in env.items())
    content = _LAUNCHD_PLIST_TEMPLATE.format(name=name, program_args=program_args, working_dir=working_dir, env_entries=env_entries)
    plists_dir.mkdir(parents=True, exist_ok=True)
    path = plists_dir / f"com.nightwire.{name}.plist"
    path.write_text(content)
    return path


def write_windows_start_script(entries: list[tuple[str, list[str], Path, dict[str, str]]], script_path: Path) -> Path:
    lines = ["# Generated by nightwire-deploy - starts each enabled service in its own window.", ""]
    for name, argv, working_dir, env in entries:
        env_assignments = "; ".join(f"$env:{k}={_ps_single_quote(v)}" for k, v in env.items())
        cmd = " ".join(argv)
        inner_parts = [p for p in (env_assignments, f"cd {_ps_single_quote(str(working_dir))}", cmd) if p]
        inner = "; ".join(inner_parts)
        lines.append(
            f"Start-Process powershell -ArgumentList '-NoExit', '-Command', {_ps_single_quote(inner)} -WindowStyle Normal  # {name}"
        )
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n")
    return script_path
